# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

### Student: Atif M. Mahmud
### SFU ID: atifm@sfu.ca

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [3]:
import pandas as pd
import numpy as np
import os
import math
from pprint import pprint
from IPython.display import display

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [4]:
# Formatting the string as per: https://www.w3schools.com/python/ref_string_format.asp
# Converting the columns pandax index to a basic list so it can easily be printed; otherwise it gave "dtype = str" at the end. Used the help of Claude for this.
print("1.1  The shape of the dataset is {shape} and the columns are {columns}".format(shape = df.shape, columns = list(df.columns)))

# Space
print("\n\n")

# Summary statistics. Data type, description, and where applicable, min, max, mean, and std. dev.
# Got some information from here: https://www.kaggle.com/datasets/yasserh/titanic-dataset
df_summary = pd.DataFrame(index = df.columns, columns = ['Data Type', 'Description', 'Min', 'Max', 'Mean', 'Standard Deviation'])

# Construct a summary data frame from the original data frame
df_summary.loc["PassengerId"] = ["Categorical", "ID of the passenger", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Survived"] = ["Categorical", "Whether or not the passenger survived. 0 = no. 1 = yes", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Pclass"] = ["Categorical", "Which class the passenger was in: 1nd, 2nd, or 3rd", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Name"] = ["Categorical", "Name of the passenger", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Sex"] = ["Categorical", "Sex of the passenger. male or female.", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Age"] = ["Numerical", "Age of the passenger", df["Age"].min(), df["Age"].max(), df["Age"].mean(), df["Age"].std()]
df_summary.loc["SibSp"] = ["Numerical", "Number of siblings/spouses aboard the titanic", df["SibSp"].min(), df["SibSp"].max(), df["SibSp"].mean(), df["SibSp"].std()]
df_summary.loc["Parch"] = ["Numerical", "Number of parents/children aboard the titanic", df["Parch"].min(), df["Parch"].max(), df["Parch"].mean(), df["Parch"].std()]
df_summary.loc["Ticket"] = ["Categorical", "Ticket Number", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Fare"] = ["Numerical", "Fare paid", df["Fare"].min(), df["Fare"].max(), df["Fare"].mean(), df["Fare"].std()]
df_summary.loc["Cabin"] = ["Categorical", "Cabin Number", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Embarked"] = ["Categorical", "Port of Embarkation: C = Cherbourg, Q = Queenstown, S = Southampton.", "N/A", "N/A", "N/A", "N/A"]

# Print it
print("1.2 The summary and descriptive data is given below.")
display(df_summary)


# Space
print("\n\n")

# The first 10 rows of the dataframe
print("1.3 The first 10 rows are given below")
display(df.head(10))

1.1  The shape of the dataset is (891, 12) and the columns are ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']



1.2 The summary and descriptive data is given below.

,Data Type,Description,Min,Max,Mean,Standard Deviation
PassengerId,Categorical,ID of the passenger,N/A,N/A,N/A,N/A
Survived,Categorical,Whether or not the passenger survived. 0 = no....,N/A,N/A,N/A,N/A
Pclass,Categorical,"Which class the passenger was in: 1nd, 2nd, or...",N/A,N/A,N/A,N/A
Name,Categorical,Name of the passenger,N/A,N/A,N/A,N/A
Sex,Categorical,Sex of the passenger. male or female.,N/A,N/A,N/A,N/A
Age,Numerical,Age of the passenger,0.42,80.0,29.699118,14.526497
SibSp,Numerical,Number of siblings/spouses aboard the titanic,0,8,0.523008,1.102743
Parch,Numerical,Number of parents/children aboard the titanic,0,6,0.381594,0.806057
Ticket,Categorical,Ticket Number,N/A,N/A,N/A,N/A
Fare,Numerical,Fare paid,0.0,512.3292,32.204208,49.693429
Cabin,Categorical,Cabin Number,N/A,N/A,N/A,N/A
Embarked,Categorical,"Port of Embarkation: C = Cherbourg, Q = Queens...",N/A,N/A,N/A,N/A

1.3 The first 10 rows are given below

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [5]:
# Select the names column
names = pd.DataFrame(df["Name"]) # I am converting it to a DataFrame to make it print nicely using display()

# Alternate way
# names = df["Name"]

# Print it
print("2.1 Names column given below")
display(names)

# Space
print("\n\n")

# Select multiple columns: Name, Sex, Age, Fare
print("2.2 Selecting multiple columns: Name, Sex, Age, Fare")
selected_columns = df[["Name", "Sex", "Age", "Fare"]]
display(selected_columns)

# Space
print("\n\n")

# Select a single row: Mr. James Moran
print("2.3 Selecting a single row: Mr. James Moran")
selected_row = df.loc[df["Name"] == "Moran, Mr. James"]
display(selected_row)

# Space
print("\n\n")

# Select a rectangle
print("2.4 Selecting a rectangular section. Name, Sex, and Age of passengers 100 to 200 (inclusive)")
rectangular_section = df.loc[100:200, "Name" : "Age"]
display(rectangular_section)

2.1 Names column given below

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                        Graham, Miss Margaret Edith
888            Johnston, Miss Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

2.2 Selecting multiple columns: Name, Sex, Age, Fare

                                                  Name     Sex   Age     Fare
0                              Braund, Mr. Owen Harris    male  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  71.2833
2                                Heikkinen, Miss Laina  female  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  53.1000
4                             Allen, Mr. William Henry    male  35.0   8.0500
..                                                 ...     ...   ...      ...
886                              Montvila, Rev. Juozas    male  27.0  13.0000
887                        Graham, Miss Margaret Edith  female  19.0  30.0000
888            Johnston, Miss Catherine Helen "Carrie"  female   NaN  23.4500
889                              Behr, Mr. Karl Howell    male  26.0  30.0000
890                                Dooley, Mr. Patrick    male  32.0   7.7500

[891 rows x 4 columns]

2.3 Selecting a single row: Mr. James Moran

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

2.4 Selecting a rectangular section. Name, Sex, and Age of passengers 100 to 200 (inclusive)

                                      Name     Sex   Age
100                 Petranec, Miss Matilda  female  28.0
101       Petroff, Mr. Pastcho ("Pentcho")    male   NaN
102              White, Mr. Richard Frasar    male  21.0
103             Johansson, Mr. Gustaf Joel    male  33.0
104         Gustafsson, Mr. Anders Vilhelm    male  37.0
..                                     ...     ...   ...
196                    Mernagh, Mr. Robert    male   NaN
197       Olsen, Mr. Karl Siegwart Andreas    male  42.0
198        Madigan, Miss Margaret "Maggie"  female   NaN
199  Yrois, Miss Henriette ("Mrs Harbeck")  female  24.0
200         Vande Walle, Mr. Nestor Cyriel    male  28.0

[101 rows x 3 columns]

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [6]:
# Show only rows where age is above 60
senior_citizens = df.loc[df["Age"] > 60]
print("3.1 Passengers above age 60")
display(senior_citizens)

# Space
print("\n\n")

# Show only roes where fare is above 100 and passenger was in 1st class
rich_people = df.loc[(df["Fare"] > 100) & (df["Pclass"] == 1)]
print("3.2 Passengers with fare above 100 and was in 1st class")
display(rich_people)

# Space
print("\n\n")

# Isolate rows with missing values in age column
missing_age = df.loc[df["Age"].isnull()]
print("3.3 Rows with missing age given below")
display(missing_age)

# Space
print("\n")

print("I can print out the remaining rows by removing such rows where age is missing")
filtered_table = df[df["Age"].notnull()]
display(filtered_table)

3.1 Passengers above age 60

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

3.2 Passengers with fare above 100 and was in 1st class

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

3.3 Rows with missing age given below

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

I can print out the remaining rows by removing such rows where age is missing

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [7]:
# Reverse the row order of the dataframe
reversed_df = df.iloc[::-1] # Shorthand slice
print("4.1 Reverse the row order of the dataset")
display(reversed_df)

# Space
print("\n\n")

# Remove one column: let's remove PassengerId
print("4.3 Data frame with the PassengerId removed")
id_removed = df.drop("PassengerId", axis=1)
display(id_removed)

# Space
print("\n\n")

print("4.3 Removing all rows with missing age")
filtered_table_2 = df[df["Age"].notnull()]
display(filtered_table_2)

4.1 Reverse the row order of the dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

4.3 Data frame with the PassengerId removed

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

4.3 Removing all rows with missing age

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [8]:
# 1 USD = 0.86 Euro according to Google
print("5.1 Creating a new column showing fares in Euros. 1 USD = 0.86 Euros")
df["Fare in Euros"] = df["Fare"] * 0.86
display(df)

# Space
print("\n\n")

# Subtract age
print("5.2 Table with average age subtracted from every age value. Let's save the filtered df to a backup for future calculations.")
df_2 = filtered_table.copy()
avg_age = df["Age"].mean()
df["Age"] = df["Age"] - avg_age
display(df)

# Space
print("\n\n")

# Subtract a custom array from two selected columns
# This is an array with value[i] = i * 2
print("5.3 Subtracting custom array from 2 selected columns (PassengerId and Fare). Array is such that value[i] = i * 2")
custom_array_1 = [x * 2 for x in range(891)]

df["PassengerId"] = df["PassengerId"] - custom_array_1
df["Fare"] = df["Fare"] - custom_array_1
display(df)

5.1 Creating a new column showing fares in Euros. 1 USD = 0.86 Euros

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare in Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.180000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.800000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.665000

5.2 Table with average age subtracted from every age value. Let's save the filtered df to a backup for future calculations.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare in Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,13.0000,NaN,S,11.180000
887,888,1,1,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,30.0000,B42,S,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000
889,890,1,1,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,30.0000,C148,C,25.800000
890,891,0,3,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,7.7500,NaN,Q,6.665000

5.3 Subtracting custom array from 2 selected columns (PassengerId and Fare). Array is such that value[i] = i * 2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare in Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,0,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,69.2833,C85,C,61.303638
2,-1,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,3.9250,NaN,S,6.815500
3,-2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,47.1000,C123,S,45.666000
4,-3,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,0.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,-885,0,2,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,-1759.0000,NaN,S,11.180000
887,-886,1,1,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,-1744.0000,B42,S,25.800000
888,-887,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,-1752.5500,NaN,S,20.167000
889,-888,1,1,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,-1748.0000,C148,C,25.800000
890,-889,0,3,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,-1772.2500,NaN,Q,6.665000

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [9]:
# Create a new column with number of characters in each name
print("6.1 Creating a new column with number of characters in each name")
df["Number of characters in name"] = df["Name"].str.len()
display(df)

# Space
print("\n\n")

# Calculate the difference between fare and age
print("6.2 Calculating difference between fare and age. Remember that the average age was subtracted from the age values.")
df["Difference betwen fare and age"] = df["Fare"] - df["Age"]
display(df)

# Space
print("\n\n")

# Round all numerical values to one decimal place
print("6.3 Round all values to 1 decimal place")
df_rounded = df.round(1)
display(df_rounded)

6.1 Creating a new column with number of characters in each name

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare in Euros,Number of characters in name
0,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000,23
1,0,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,69.2833,C85,C,61.303638,51
2,-1,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,3.9250,NaN,S,6.815500,21
3,-2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,47.1000,C123,S,45.666000,44
4,-3,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,0.0500,NaN,S,6.923000,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,-885,0,2,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,-1759.0000,NaN,S,11.180000,21
887,-886,1,1,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,-1744.0000,B42,S,25.800000,27
888,-887,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,-1752.5500,NaN,S,20.167000,39
889,-888,1,1,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,-1748.0000,C148,C,25.800000,21
890,-889,0,3,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,-1772.2500,NaN,Q,6.665000,19

6.2 Calculating difference between fare and age. Remember that the average age was subtracted from the age values.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare in Euros,Number of characters in name,Difference betwen fare and age
0,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000,23,14.949118
1,0,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,69.2833,C85,C,61.303638,51,60.982418
2,-1,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,3.9250,NaN,S,6.815500,21,7.624118
3,-2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,47.1000,C123,S,45.666000,44,41.799118
4,-3,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,0.0500,NaN,S,6.923000,24,-5.250882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,-885,0,2,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,-1759.0000,NaN,S,11.180000,21,-1756.300882
887,-886,1,1,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,-1744.0000,B42,S,25.800000,27,-1733.300882
888,-887,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,-1752.5500,NaN,S,20.167000,39,NaN
889,-888,1,1,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,-1748.0000,C148,C,25.800000,21,-1744.300882
890,-889,0,3,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,-1772.2500,NaN,Q,6.665000,19,-1774.550882

6.3 Round all values to 1 decimal place

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare in Euros,Number of characters in name,Difference betwen fare and age
0,1,0,3,"Braund, Mr. Owen Harris",male,-7.7,1,0,A/5 21171,7.2,NaN,S,6.2,23,14.9
1,0,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.3,1,0,PC 17599,69.3,C85,C,61.3,51,61.0
2,-1,1,3,"Heikkinen, Miss Laina",female,-3.7,0,0,STON/O2. 3101282,3.9,NaN,S,6.8,21,7.6
3,-2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.3,1,0,113803,47.1,C123,S,45.7,44,41.8
4,-3,0,3,"Allen, Mr. William Henry",male,5.3,0,0,373450,0.1,NaN,S,6.9,24,-5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,-885,0,2,"Montvila, Rev. Juozas",male,-2.7,0,0,211536,-1759.0,NaN,S,11.2,21,-1756.3
887,-886,1,1,"Graham, Miss Margaret Edith",female,-10.7,0,0,112053,-1744.0,B42,S,25.8,27,-1733.3
888,-887,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,-1752.6,NaN,S,20.2,39,NaN
889,-888,1,1,"Behr, Mr. Karl Howell",male,-3.7,0,0,111369,-1748.0,C148,C,25.8,21,-1744.3
890,-889,0,3,"Dooley, Mr. Patrick",male,2.3,0,0,370376,-1772.2,NaN,Q,6.7,19,-1774.6

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [10]:
# Convert categorical gender values to numeric codes
print("7.1 Convert gender to numeric code")
df["Sex"] = df["Sex"].map(lambda x: 1 if x == "male" else 0)
display(df)

# Space
print("\n\n")

# Create a column that categorize age into groups
print("7.2 Create a new column that categorizes age into groups. Using table with proper age and NaN removed.")
df_2["Age category"] = df_2["Age"].map(lambda x: "Child" if x > 0 and x < 18 else ("Adult" if x >= 18 and x < 60 else "Senior"))
display(df_2)

7.1 Convert gender to numeric code

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare in Euros,Number of characters in name,Difference betwen fare and age
0,1,0,3,"Braund, Mr. Owen Harris",1,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000,23,14.949118
1,0,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,8.300882,1,0,PC 17599,69.2833,C85,C,61.303638,51,60.982418
2,-1,1,3,"Heikkinen, Miss Laina",0,-3.699118,0,0,STON/O2. 3101282,3.9250,NaN,S,6.815500,21,7.624118
3,-2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,5.300882,1,0,113803,47.1000,C123,S,45.666000,44,41.799118
4,-3,0,3,"Allen, Mr. William Henry",1,5.300882,0,0,373450,0.0500,NaN,S,6.923000,24,-5.250882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,-885,0,2,"Montvila, Rev. Juozas",1,-2.699118,0,0,211536,-1759.0000,NaN,S,11.180000,21,-1756.300882
887,-886,1,1,"Graham, Miss Margaret Edith",0,-10.699118,0,0,112053,-1744.0000,B42,S,25.800000,27,-1733.300882
888,-887,0,3,"Johnston, Miss Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,-1752.5500,NaN,S,20.167000,39,NaN
889,-888,1,1,"Behr, Mr. Karl Howell",1,-3.699118,0,0,111369,-1748.0000,C148,C,25.800000,21,-1744.300882
890,-889,0,3,"Dooley, Mr. Patrick",1,2.300882,0,0,370376,-1772.2500,NaN,Q,6.665000,19,-1774.550882

7.2 Create a new column that categorizes age into groups. Using table with proper age and NaN removed.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,Adult
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult

### Part 8: Try without Pandas ###

The tasks I will do:

2.1 Selecting the names column  
2.2 Selecting multiple columns
2.3 Selecting a single row

In [18]:
df_as_list = []

for column in df.columns:
    list = df[column].tolist()
    df_as_list.append(list)

display(df_as_list)

# Selecting the names column
print("8 (2.1) Selecting the names column. It's the 4th column")
names_column = df_as_list[3]
display(names_column)

# Space
print("\n\n")

# Selecting the multiple columns. Name, Age, Fare
print("8 (2.2) Selecting multiple columns. Name, Age, Fare")
name_age_fare_column = names_column
age_column = df_as_list[5]
name_age_fare_column.append(age_column)
fare_column = df_as_list[9]
name_age_fare_column.append(fare_column)
display(name_age_fare_column)

# Space
print("\n\n")

# Selecting a single row: PassengerId = 2, Mrs. John Bradley Cumings
print("8 (2.3) Selecting a single row. Mrs. John Bradley Cumings")
single_row = [row[1] for row in df_as_list]
display(single_row)

[[1,
  0,
  -1,
  -2,
  -3,
  -4,
  -5,
  -6,
  -7,
  -8,
  -9,
  -10,
  -11,
  -12,
  -13,
  -14,
  -15,
  -16,
  -17,
  -18,
  -19,
  -20,
  -21,
  -22,
  -23,
  -24,
  -25,
  -26,
  -27,
  -28,
  -29,
  -30,
  -31,
  -32,
  -33,
  -34,
  -35,
  -36,
  -37,
  -38,
  -39,
  -40,
  -41,
  -42,
  -43,
  -44,
  -45,
  -46,
  -47,
  -48,
  -49,
  -50,
  -51,
  -52,
  -53,
  -54,
  -55,
  -56,
  -57,
  -58,
  -59,
  -60,
  -61,
  -62,
  -63,
  -64,
  -65,
  -66,
  -67,
  -68,
  -69,
  -70,
  -71,
  -72,
  -73,
  -74,
  -75,
  -76,
  -77,
  -78,
  -79,
  -80,
  -81,
  -82,
  -83,
  -84,
  -85,
  -86,
  -87,
  -88,
  -89,
  -90,
  -91,
  -92,
  -93,
  -94,
  -95,
  -96,
  -97,
  -98,
  -99,
  -100,
  -101,
  -102,
  -103,
  -104,
  -105,
  -106,
  -107,
  -108,
  -109,
  -110,
  -111,
  -112,
  -113,
  -114,
  -115,
  -116,
  -117,
  -118,
  -119,
  -120,
  -121,
  -122,
  -123,
  -124,
  -125,
  -126,
  -127,
  -128,
  -129,
  -130,
  -131,
  -132,
  -133,
  -134,
  -135,
  -136,
  -137,
  -138,
  -139,
  -140,
  -141,
  -142,
  -143,
  -144,
  -145,
  -146,
  -147,
  -148,
  -149,
  -150,
  -151,
  -152,
  -153,
  -154,
  -155,
  -156,
  -157,
  -158,
  -159,
  -160,
  -161,
  -162,
  -163,
  -164,
  -165,
  -166,
  -167,
  -168,
  -169,
  -170,
  -171,
  -172,
  -173,
  -174,
  -175,
  -176,
  -177,
  -178,
  -179,
  -180,
  -181,
  -182,
  -183,
  -184,
  -185,
  -186,
  -187,
  -188,
  -189,
  -190,
  -191,
  -192,
  -193,
  -194,
  -195,
  -196,
  -197,
  -198,
  -199,
  -200,
  -201,
  -202,
  -203,
  -204,
  -205,
  -206,
  -207,
  -208,
  -209,
  -210,
  -211,
  -212,
  -213,
  -214,
  -215,
  -216,
  -217,
  -218,
  -219,
  -220,
  -221,
  -222,
  -223,
  -224,
  -225,
  -226,
  -227,
  -228,
  -229,
  -230,
  -231,
  -232,
  -233,
  -234,
  -235,
  -236,
  -237,
  -238,
  -239,
  -240,
  -241,
  -242,
  -243,
  -244,
  -245,
  -246,
  -247,
  -248,
  -249,
  -250,
  -251,
  -252,
  -253,
  -254,
  -255,
  -256,
  -257,
  -258,
  -259,
  -260,
  -261,
  -262,
  -263,
  -264,
  -265,
  -266,
  -267,
  -268,
  -269,
  -270,
  -271,
  -272,
  -273,
  -274,
  -275,
  -276,
  -277,
  -278,
  -279,
  -280,
  -281,
  -282,
  -283,
  -284,
  -285,
  -286,
  -287,
  -288,
  -289,
  -290,
  -291,
  -292,
  -293,
  -294,
  -295,
  -296,
  -297,
  -298,
  -299,
  -300,
  -301,
  -302,
  -303,
  -304,
  -305,
  -306,
  -307,
  -308,
  -309,
  -310,
  -311,
  -312,
  -313,
  -314,
  -315,
  -316,
  -317,
  -318,
  -319,
  -320,
  -321,
  -322,
  -323,
  -324,
  -325,
  -326,
  -327,
  -328,
  -329,
  -330,
  -331,
  -332,
  -333,
  -334,
  -335,
  -336,
  -337,
  -338,
  -339,
  -340,
  -341,
  -342,
  -343,
  -344,
  -345,
  -346,
  -347,
  -348,
  -349,
  -350,
  -351,
  -352,
  -353,
  -354,
  -355,
  -356,
  -357,
  -358,
  -359,
  -360,
  -361,
  -362,
  -363,
  -364,
  -365,
  -366,
  -367,
  -368,
  -369,
  -370,
  -371,
  -372,
  -373,
  -374,
  -375,
  -376,
  -377,
  -378,
  -379,
  -380,
  -381,
  -382,
  -383,
  -384,
  -385,
  -386,
  -387,
  -388,
  -389,
  -390,
  -391,
  -392,
  -393,
  -394,
  -395,
  -396,
  -397,
  -398,
  -399,
  -400,
  -401,
  -402,
  -403,
  -404,
  -405,
  -406,
  -407,
  -408,
  -409,
  -410,
  -411,
  -412,
  -413,
  -414,
  -415,
  -416,
  -417,
  -418,
  -419,
  -420,
  -421,
  -422,
  -423,
  -424,
  -425,
  -426,
  -427,
  -428,
  -429,
  -430,
  -431,
  -432,
  -433,
  -434,
  -435,
  -436,
  -437,
  -438,
  -439,
  -440,
  -441,
  -442,
  -443,
  -444,
  -445,
  -446,
  -447,
  -448,
  -449,
  -450,
  -451,
  -452,
  -453,
  -454,
  -455,
  -456,
  -457,
  -458,
  -459,
  -460,
  -461,
  -462,
  -463,
  -464,
  -465,
  -466,
  -467,
  -468,
  -469,
  -470,
  -471,
  -472,
  -473,
  -474,
  -475,
  -476,
  -477,
  -478,
  -479,
  -480,
  -481,
  -482,
  -483,
  -484,
  -485,
  -486,
  -487,
  -488,
  -489,
  -490,
  -491,
  -492,
  -493,
  -494,
  -495,
  -496,
  -497,
  -498,
  -499,
  -500,
  -501,
  -502,
  -503,
  -504,
  -505,
  -506,
  -507,
  -508,
  -509,
  -510,
  -511,
  -512,
  -513,
  -514,
  -515,
  -516,
  -517,
  -518,
  -519,
  -520,
  -521,
  -522,
  -523,
  -524,
  -525,
  -526,
  -527,
  -528,
  -529,
  -530,
  -531,
  -532,
  -533,
  -534,
  -535,
  -536,
  -537,
  -538,
  -539,
  -540,
  -541,
  -542,
  -543,
  -544,
  -545,
  -546,
  -547,
  -548,
  -549,
  -550,
  -551,
  -552,
  -553,
  -554,
  -555,
  -556,
  -557,
  -558,
  -559,
  -560,
  -561,
  -562,
  -563,
  -564,
  -565,
  -566,
  -567,
  -568,
  -569,
  -570,
  -571,
  -572,
  -573,
  -574,
  -575,
  -576,
  -577,
  -578,
  -579,
  -580,
  -581,
  -582,
  -583,
  -584,
  -585,
  -586,
  -587,
  -588,
  -589,
  -590,
  -591,
  -592,
  -593,
  -594,
  -595,
  -596,
  -597,
  -598,
  -599,
  -600,
  -601,
  -602,
  -603,
  -604,
  -605,
  -606,
  -607,
  -608,
  -609,
  -610,
  -611,
  -612,
  -613,
  -614,
  -615,
  -616,
  -617,
  -618,
  -619,
  -620,
  -621,
  -622,
  -623,
  -624,
  -625,
  -626,
  -627,
  -628,
  -629,
  -630,
  -631,
  -632,
  -633,
  -634,
  -635,
  -636,
  -637,
  -638,
  -639,
  -640,
  -641,
  -642,
  -643,
  -644,
  -645,
  -646,
  -647,
  -648,
  -649,
  -650,
  -651,
  -652,
  -653,
  -654,
  -655,
  -656,
  -657,
  -658,
  -659,
  -660,
  -661,
  -662,
  -663,
  -664,
  -665,
  -666,
  -667,
  -668,
  -669,
  -670,
  -671,
  -672,
  -673,
  -674,
  -675,
  -676,
  -677,
  -678,
  -679,
  -680,
  -681,
  -682,
  -683,
  -684,
  -685,
  -686,
  -687,
  -688,
  -689,
  -690,
  -691,
  -692,
  -693,
  -694,
  -695,
  -696,
  -697,
  -698,
  -699,
  -700,
  -701,
  -702,
  -703,
  -704,
  -705,
  -706,
  -707,
  -708,
  -709,
  -710,
  -711,
  -712,
  -713,
  -714,
  -715,
  -716,
  -717,
  -718,
  -719,
  -720,
  -721,
  -722,
  -723,
  -724,
  -725,
  -726,
  -727,
  -728,
  -729,
  -730,
  -731,
  -732,
  -733,
  -734,
  -735,
  -736,
  -737,
  -738,
  -739,
  -740,
  -741,
  -742,
  -743,
  -744,
  -745,
  -746,
  -747,
  -748,
  -749,
  -750,
  -751,
  -752,
  -753,
  -754,
  -755,
  -756,
  -757,
  -758,
  -759,
  -760,
  -761,
  -762,
  -763,
  -764,
  -765,
  -766,
  -767,
  -768,
  -769,
  -770,
  -771,
  -772,
  -773,
  -774,
  -775,
  -776,
  -777,
  -778,
  -779,
  -780,
  -781,
  -782,
  -783,
  -784,
  -785,
  -786,
  -787,
  -788,
  -789,
  -790,
  -791,
  -792,
  -793,
  -794,
  -795,
  -796,
  -797,
  -798,
  -799,
  -800,
  -801,
  -802,
  -803,
  -804,
  -805,
  -806,
  -807,
  -808,
  -809,
  -810,
  -811,
  -812,
  -813,
  -814,
  -815,
  -816,
  -817,
  -818,
  -819,
  -820,
  -821,
  -822,
  -823,
  -824,
  -825,
  -826,
  -827,
  -828,
  -829,
  -830,
  -831,
  -832,
  -833,
  -834,
  -835,
  -836,
  -837,
  -838,
  -839,
  -840,
  -841,
  -842,
  -843,
  -844,
  -845,
  -846,
  -847,
  -848,
  -849,
  -850,
  -851,
  -852,
  -853,
  -854,
  -855,
  -856,
  -857,
  -858,
  -859,
  -860,
  -861,
  -862,
  -863,
  -864,
  -865,
  -866,
  -867,
  -868,
  -869,
  -870,
  -871,
  -872,
  -873,
  -874,
  -875,
  -876,
  -877,
  -878,
  -879,
  -880,
  -881,
  -882,
  -883,
  -884,
  -885,
  -886,
  -887,
  -888,
  -889],
 [0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0],
 [3,
  1,
  3,
  1,
  3,
  3,
  1,
  3,
  3,
  2,
  3,
  1,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  2,
  2,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  1,
  1,
  3,
  2,
  1,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  2,
  1,
  1,
  2,
  3,
  2,
  3,
  3,
  1,
  1,
  3,
  1,
  3,
  2,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  1,
  2,
  2,
  3,
  3,
  1,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  3,
  3,
  3,
  2,
  1,
  3,
  2,
  3,
  2,
  2,
  1,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  2,
  2,
  2,
  1,
  1,
  3,
  1,
  3,
  3,
  3,
  3,
  2,
  2,
  3,
  3,
  2,
  2,
  2,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  1,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  1,
  2,
  3,
  3,
  2,
  3,
  2,
  3,
  1,
  3,
  1,
  3,
  3,
  2,
  2,
  3,
  2,
  1,
  1,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  3,
  2,
  3,
  2,
  3,
  1,
  3,
  2,
  1,
  2,
  3,
  2,
  3,
  3,
  1,
  3,
  2,
  3,
  2,
  3,
  1,
  3,
  2,
  3,
  2,
  3,
  2,
  2,
  2,
  2,
  3,
  3,
  2,
  3,
  3,
  1,
  3,
  2,
  1,
  2,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  1,
  1,
  2,
  3,
  3,
  1,
  1,
  3,
  2,
  3,
  3,
  1,
  1,
  1,
  3,
  2,
  1,
  3,
  1,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  2,
  3,
  1,
  1,
  2,
  3,
  3,
  1,
  3,
  1,
  1,
  1,
  3,
  3,
  3,
  2,
  3,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  2,
  3,
  2,
  3,
  2,
  2,
  1,
  1,
  3,
  3,
  2,
  2,
  3,
  1,
  3,
  2,
  3,
  1,
  3,
  1,
  1,
  3,
  1,
  3,
  1,
  1,
  3,
  1,
  2,
  1,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  3,
  1,
  1,
  3,
  3,
  1,
  3,
  1,
  3,
  1,
  3,
  3,
  1,
  3,
  3,
  1,
  3,
  2,
  3,
  2,
  3,
  2,
  1,
  3,
  3,
  1,
  3,
  3,
  3,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  2,
  2,
  3,
  3,
  1,
  3,
  2,
  3,
  1,
  1,
  3,
  2,
  1,
  2,
  2,
  3,
  3,
  2,
  3,
  1,
  2,
  1,
  3,
  1,
  2,
  3,
  1,
  1,
  3,
  3,
  1,
  1,
  2,
  3,
  1,
  3,
  1,
  2,
  3,
  3,
  2,
  1,
  3,
  3,
  3,
  3,
  2,
  2,
  3,
  1,
  2,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  3,
  3,
  3,
  1,
  1,
  3,
  3,
  1,
  3,
  1,
  3,
  3,
  3,
  3,
  3,
  1,
  1,
  2,
  1,
  3,
  3,
  3,
  3,
  1,
  1,
  3,
  1,
  2,
  3,
  2,
  3,
  1,
  3,
  3,
  1,
  3,
  3,
  2,
  1,
  3,
  2,
  2,
  3,
  3,
  3,
  3,
  2,
  1,
  1,
  3,
  1,
  1,
  3,
  3,
  2,
  1,
  1,
  2,
  2,
  3,
  2,
  1,
  2,
  3,
  3,
  3,
  1,
  1,
  1,
  1,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  2,
  1,
  1,
  3,
  3,
  3,
  2,
  1,
  3,
  3,
  2,
  1,
  2,
  1,
  3,
  1,
  2,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  1,
  2,
  3,
  1,
  3,
  1,
  3,
  3,
  1,
  2,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  2,
  2,
  3,
  1,
  3,
  3,
  3,
  1,
  2,
  1,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  1,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  2,
  3,
  3,
  2,
  1,
  1,
  3,
  1,
  3,
  3,
  2,
  2,
  3,
  3,
  1,
  2,
  1,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  1,
  3,
  3,
  2,
  2,
  3,
  3,
  3,
  1,
  1,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  3,
  3,
  2,
  2,
  1,
  1,
  3,
  1,
  1,
  1,
  3,
  2,
  3,
  1,
  2,
  3,
  3,
  2,
  3,
  2,
  2,
  1,
  3,
  2,
  3,
  2,
  3,
  1,
  3,
  2,
  2,
  2,
  3,
  3,
  1,
  3,
  3,
  1,
  1,
  1,
  3,
  3,
  1,
  3,
  2,
  1,
  3,
  2,
  3,
  3,
  3,
  2,
  2,
  3,
  2,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  3,
  2,
  3,
  1,
  3,
  2,
  1,
  3,
  3,
  3,
  2,
  2,
  1,
  3,
  3,
  3,
  1,
  3,
  2,
  1,
  3,
  3,
  2,
  3,
  3,
  1,
  3,
  2,
  3,
  3,
  1,
  3,
  1,
  3,
  3,
  3,
  3,
  2,
  3,
  1,
  3,
  2,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  2,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  1,
  3,
  3,
  3,
  1,
  2,
  3,
  1,
  1,
  3,
  3,
  3,
  2,
  1,
  3,
  2,
  2,
  2,
  1,
  3,
  3,
  3,
  1,
  1,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  2,
  3,
  3,
  2,
  1,
  3,
  1,
  3],
 ['Braund, Mr. Owen Harris',
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'Heikkinen, Miss Laina',
  'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'Allen, Mr. William Henry',
  'Moran, Mr. James',
  'McCarthy, Mr. Timothy J',
  'Palsson, Master Gosta Leonard',
  'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'Nasser, Mrs. Nicholas (Adele Achem)',
  'Sandstrom, Miss Marguerite Rut',
  'Bonnell, Miss Elizabeth',
  'Saundercock, Mr. William Henry',
  'Andersson, Mr. Anders Johan',
  'Vestrom, Miss Hulda Amanda Adolfina',
  'Hewlett, Mrs. (Mary D Kingcome) ',
  'Rice, Master Eugene',
  'Williams, Mr. Charles Eugene',
  'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'Masselmani, Mrs. Fatima',
  'Fynney, Mr. Joseph J',
  'Beesley, Mr. Lawrence',
  'McGowan, Miss Anna "Annie"',
  'Sloper, Mr. William Thompson',
  'Palsson, Miss Torborg Danira',
  'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'Emir, Mr. Farred Chehab',
  'Fortune, Mr. Charles Alexander',
  'O\'Dwyer, Miss Ellen "Nellie"',
  'Todoroff, Mr. Lalio',
  'Uruchurtu, Don. Manuel E',
  'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'Glynn, Miss Mary Agatha',
  'Wheadon, Mr. Edward H',
  'Meyer, Mr. Edgar Joseph',
  'Holverson, Mr. Alexander Oskar',
  'Mamee, Mr. Hanna',
  'Cann, Mr. Ernest Charles',
  'Vander Planke, Miss Augusta Maria',
  'Nicola-Yarred, Miss Jamila',
  'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'Kraeff, Mr. Theodor',
  'Laroche, Miss Simonne Marie Anne Andree',
  'Devaney, Miss Margaret Delia',
  'Rogers, Mr. William John',
  'Lennon, Mr. Denis',
  "O'Driscoll, Miss Bridget",
  'Samaan, Mr. Youssef',
  'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'Panula, Master Juha Niilo',
  'Nosworthy, Mr. Richard Cater',
  'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'Ostby, Mr. Engelhart Cornelius',
  'Woolner, Mr. Hugh',
  'Rugg, Miss Emily',
  'Novel, Mr. Mansouer',
  'West, Miss Constance Mirium',
  'Goodwin, Master William Frederick',
  'Sirayanian, Mr. Orsen',
  'Icard, Miss Amelie',
  'Harris, Mr. Henry Birkhardt',
  'Skoog, Master Harald',
  'Stewart, Mr. Albert A',
  'Moubarek, Master Gerios',
  'Nye, Mrs. (Elizabeth Ramell)',
  'Crease, Mr. Ernest James',
  'Andersson, Miss Erna Alexandra',
  'Kink, Mr. Vincenz',
  'Jenkin, Mr. Stephen Curnow',
  'Goodwin, Miss Lillian Amy',
  'Hood, Mr. Ambrose Jr',
  'Chronopoulos, Mr. Apostolos',
  'Bing, Mr. Lee',
  'Moen, Mr. Sigurd Hansen',
  'Staneff, Mr. Ivan',
  'Moutal, Mr. Rahamin Haim',
  'Caldwell, Master Alden Gates',
  'Dowdell, Miss Elizabeth',
  'Waelens, Mr. Achille',
  'Sheerlinck, Mr. Jan Baptist',
  'McDermott, Miss Brigdet Delia',
  'Carrau, Mr. Francisco M',
  'Ilett, Miss Bertha',
  'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
  'Ford, Mr. William Neal',
  'Slocovski, Mr. Selman Francis',
  'Fortune, Miss Mabel Helen',
  'Celotti, Mr. Francesco',
  'Christmann, Mr. Emil',
  'Andreasson, Mr. Paul Edvin',
  'Chaffee, Mr. Herbert Fuller',
  'Dean, Mr. Bertram Frank',
  'Coxon, Mr. Daniel',
  'Shorney, Mr. Charles Joseph',
  'Goldschmidt, Mr. George B',
  'Greenfield, Mr. William Bertram',
  'Doling, Mrs. John T (Ada Julia Bone)',
  'Kantor, Mr. Sinai',
  'Petranec, Miss Matilda',
  'Petroff, Mr. Pastcho ("Pentcho")',
  'White, Mr. Richard Frasar',
  'Johansson, Mr. Gustaf Joel',
  'Gustafsson, Mr. Anders Vilhelm',
  'Mionoff, Mr. Stoytcho',
  'Salkjelsvik, Miss Anna Kristine',
  'Moss, Mr. Albert Johan',
  'Rekic, Mr. Tido',
  'Moran, Miss Bertha',
  'Porter, Mr. Walter Chamberlain',
  'Zabour, Miss Hileni',
  'Barton, Mr. David John',
  'Jussila, Miss Katriina',
  'Attalah, Miss Malake',
  'Pekoniemi, Mr. Edvard',
  'Connors, Mr. Patrick',
  'Turpin, Mr. William John Robert',
  'Baxter, Mr. Quigg Edmond',
  'Andersson, Miss Ellis Anna Maria',
  'Hickman, Mr. Stanley George',
  'Moore, Mr. Leonard Charles',
  'Nasser, Mr. Nicholas',
  'Webber, Miss Susan',

8 (2.1) Selecting the names column. It's the 4th column

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Nasser, Mrs. Nicholas (Adele Achem)',
 'Sandstrom, Miss Marguerite Rut',
 'Bonnell, Miss Elizabeth',
 'Saundercock, Mr. William Henry',
 'Andersson, Mr. Anders Johan',
 'Vestrom, Miss Hulda Amanda Adolfina',
 'Hewlett, Mrs. (Mary D Kingcome) ',
 'Rice, Master Eugene',
 'Williams, Mr. Charles Eugene',
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
 'Masselmani, Mrs. Fatima',
 'Fynney, Mr. Joseph J',
 'Beesley, Mr. Lawrence',
 'McGowan, Miss Anna "Annie"',
 'Sloper, Mr. William Thompson',
 'Palsson, Miss Torborg Danira',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Emir, Mr. Farred Chehab',
 'Fortune, Mr. Charles Alexander',
 'O\'Dwyer, Miss Ellen "Nellie"',
 'Todoroff, Mr. Lalio',
 'Uruchurtu, Don. Manuel E',
 'Spencer, Mrs. William Augustus (Marie Eugenie)',
 'Glynn, Miss Mary Agatha',
 'Wheadon, Mr. Edward H',
 'Meyer, Mr. Edgar Joseph',
 'Holverson, Mr. Alexander Oskar',
 'Mamee, Mr. Hanna',
 'Cann, Mr. Ernest Charles',
 'Vander Planke, Miss Augusta Maria',
 'Nicola-Yarred, Miss Jamila',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
 'Kraeff, Mr. Theodor',
 'Laroche, Miss Simonne Marie Anne Andree',
 'Devaney, Miss Margaret Delia',
 'Rogers, Mr. William John',
 'Lennon, Mr. Denis',
 "O'Driscoll, Miss Bridget",
 'Samaan, Mr. Youssef',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Panula, Master Juha Niilo',
 'Nosworthy, Mr. Richard Cater',
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
 'Ostby, Mr. Engelhart Cornelius',
 'Woolner, Mr. Hugh',
 'Rugg, Miss Emily',
 'Novel, Mr. Mansouer',
 'West, Miss Constance Mirium',
 'Goodwin, Master William Frederick',
 'Sirayanian, Mr. Orsen',
 'Icard, Miss Amelie',
 'Harris, Mr. Henry Birkhardt',
 'Skoog, Master Harald',
 'Stewart, Mr. Albert A',
 'Moubarek, Master Gerios',
 'Nye, Mrs. (Elizabeth Ramell)',
 'Crease, Mr. Ernest James',
 'Andersson, Miss Erna Alexandra',
 'Kink, Mr. Vincenz',
 'Jenkin, Mr. Stephen Curnow',
 'Goodwin, Miss Lillian Amy',
 'Hood, Mr. Ambrose Jr',
 'Chronopoulos, Mr. Apostolos',
 'Bing, Mr. Lee',
 'Moen, Mr. Sigurd Hansen',
 'Staneff, Mr. Ivan',
 'Moutal, Mr. Rahamin Haim',
 'Caldwell, Master Alden Gates',
 'Dowdell, Miss Elizabeth',
 'Waelens, Mr. Achille',
 'Sheerlinck, Mr. Jan Baptist',
 'McDermott, Miss Brigdet Delia',
 'Carrau, Mr. Francisco M',
 'Ilett, Miss Bertha',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Ford, Mr. William Neal',
 'Slocovski, Mr. Selman Francis',
 'Fortune, Miss Mabel Helen',
 'Celotti, Mr. Francesco',
 'Christmann, Mr. Emil',
 'Andreasson, Mr. Paul Edvin',
 'Chaffee, Mr. Herbert Fuller',
 'Dean, Mr. Bertram Frank',
 'Coxon, Mr. Daniel',
 'Shorney, Mr. Charles Joseph',
 'Goldschmidt, Mr. George B',
 'Greenfield, Mr. William Bertram',
 'Doling, Mrs. John T (Ada Julia Bone)',
 'Kantor, Mr. Sinai',
 'Petranec, Miss Matilda',
 'Petroff, Mr. Pastcho ("Pentcho")',
 'White, Mr. Richard Frasar',
 'Johansson, Mr. Gustaf Joel',
 'Gustafsson, Mr. Anders Vilhelm',
 'Mionoff, Mr. Stoytcho',
 'Salkjelsvik, Miss Anna Kristine',
 'Moss, Mr. Albert Johan',
 'Rekic, Mr. Tido',
 'Moran, Miss Bertha',
 'Porter, Mr. Walter Chamberlain',
 'Zabour, Miss Hileni',
 'Barton, Mr. David John',
 'Jussila, Miss Katriina',
 'Attalah, Miss Malake',
 'Pekoniemi, Mr. Edvard',
 'Connors, Mr. Patrick',
 'Turpin, Mr. William John Robert',
 'Baxter, Mr. Quigg Edmond',
 'Andersson, Miss Ellis Anna Maria',
 'Hickman, Mr. Stanley George',
 'Moore, Mr. Leonard Charles',
 'Nasser, Mr. Nicholas',
 'Webber, Miss Susan',
 'White, Mr. Percival Wayland',
 'Nicola-Yarred, Master Elias',
 'McMahon, Mr. Martin',
 'Madsen, Mr. Fridtjof Arne',
 'Peter, Miss Anna',
 'Ekstrom, Mr. Johan',
 'Drazenoic, Mr. Jozef',
 'Coelho, Mr. Domingos Fernandeo',
 'Robins, Mrs. Alexander A (Grace Charity Laury)',
 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
 'Sobey, Mr. Samuel James Hayden',
 'Richard, Mr. Emile',
 'Newsom, Miss Helen Monypeny',
 'Futrelle, Mr. Jacques Heath',
 'Osen, Mr. Olaf Elon',
 'Giglio, Mr. Victor',
 'Boulos, Mrs. Joseph (Sultana)',
 'Nysten, Miss Anna Sofia',
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
 'Burke, Mr. Jeremiah',
 'Andrew, Mr. Edgardo Samuel',
 'Nicholls, Mr. Joseph Charles',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Ford, Miss Robina Maggie "Ruby"',
 'Navratil, Mr. Michel ("Louis M Hoffman")',
 'Byles, Rev. Thomas Roussel Davids',
 'Bateman, Rev. Robert James',
 'Pears, Mrs. Thomas (Edith Wearne)',
 'Meo, Mr. Alfonzo',
 'van Billiard, Mr. Austin Blyler',
 'Olsen, Mr. Ole Martin',
 'Williams, Mr. Charles Duane',
 'Gilnagh, Miss Katherine "Katie"',
 'Corn, Mr. Harry',
 'Smiljanic, Mr. Mile',
 'Sage, Master Thomas Henry',
 'Cribb, Mr. John Hatfield',
 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
 'Bengtsson, Mr. John Viktor',
 'Calic, Mr. Jovo',
 'Panula, Master Eino Viljami',
 'Goldsmith, Master Frank John William "Frankie"',
 'Chibnall, Mrs. (Edith Martha Bowerman)',
 'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
 'Baumann, Mr. John D',
 'Ling, Mr. Lee',
 'Van der hoef, Mr. Wyckoff',
 'Rice, Master Arthur',
 'Johnson, Miss Eleanor Ileen',
 'Sivola, Mr. Antti Wilhelm',
 'Smith, Mr. James Clinch',
 'Klasen, Mr. Klas Albin',
 'Lefebre, Master Henry Forbes',
 'Isham, Miss Ann Elizabeth',
 'Hale, Mr. Reginald',
 'Leonard, Mr. Lionel',
 'Sage, Miss Constance Gladys',
 'Pernot, Mr. Rene',
 'Asplund, Master Clarence Gustaf Hugo',
 'Becker, Master Richard F',
 'Kink-Heilmann, Miss Luise Gretchen',
 'Rood, Mr. Hugh Roscoe',
 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)',
 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
 'Bourke, Mr. John',
 'Turcin, Mr. Stjepan',
 'Pinsky, Mrs. (Rosa)',
 'Carbines, Mr. William',
 'Andersen-Jensen, Miss Carla Christine Nielsine',
 'Navratil, Master Michel M',
 'Brown, Mrs. James Joseph (Margaret Tobin)',
 'Lurette, Miss Elise',
 'Mernagh, Mr. Robert',
 'Olsen, Mr. Karl Siegwart Andreas',
 'Madigan, Miss Margaret "Maggie"',
 'Yrois, Miss Henriette ("Mrs Harbeck")',
 'Vande Walle, Mr. Nestor Cyriel',
 'Sage, Mr. Frederick',
 'Johanson, Mr. Jakob Alfred',
 'Youseff, Mr. Gerious',
 'Cohen, Mr. Gurshon "Gus"',
 'Strom, Miss Telma Matilda',
 'Backstrom, Mr. Karl Alfred',
 'Albimona, Mr. Nassef Cassem',
 'Carr, Miss Helen "Ellen"',
 'Blank, Mr. Henry',
 'Ali, Mr. Ahmed',
 'Cameron, Miss Clear Annie',
 'Perkin, Mr. John Henry',
 'Givard, Mr. Hans Kristensen',
 'Kiernan, Mr. Philip',
 'Newell, Miss Madeleine',
 'Honkanen, Miss Eliina',
 'Jacobsohn, Mr. Sidney Samuel',
 'Bazzani, Miss Albina',
 'Harris, Mr. Walter',
 'Sunderland, Mr. Victor Francis',
 'Bracken, Mr. James H',
 'Green, Mr. George Henry',
 'Nenkoff, Mr. Christo',
 'Hoyt, Mr. Frederick Maxfield',
 'Berglund, Mr. Karl Ivar Sven',
 'Mellors, Mr. William John',
 'Lovell, Mr. John Hall ("Henry")',
 'Fahlstrom, Mr. Arne Jonas',
 'Lefebre, Miss Mathilde',
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
 'Larsson, Mr. Bengt Edvin',
 'Sjostedt, Mr. Ernst Adolf',
 'Asplund, Miss Lillian Gertrud',
 'Leyson, Mr. Robert William Norman',
 'Harknett, Miss Alice Phoebe',
 'Hold, Mr. Stephen',
 'Collyer, Miss Marjorie "Lottie"',
 'Pengelly, Mr. Frederick William',
 'Hunt, Mr. George Henry',
 'Zabour, Miss Thamine',
 'Murphy, Miss Katherine "Kate"',
 'Coleridge, Mr. Reginald Charles',
 'Maenpaa, Mr. Matti Alexanteri',
 'Attalah, Mr. Sleiman',
 'Minahan, Dr. William Edward',
 'Lindahl, Miss Agda Thorilda Viktoria',
 'Hamalainen, Mrs. William (Anna)',
 'Beckwith, Mr. Richard Leonard',
 'Carter, Rev. Ernest Courtenay',
 'Reed, Mr. James George',
 'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
 'Stead, Mr. William Thomas',
 'Lobb, Mr. William Arthur',
 'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
 'Touma, Mrs. Darwis (Hanne Youssef Razi)',
 'Thorne, Mrs. Gertrude Maybelle',
 'Cherry, Miss Gladys',
 'Ward, Miss Anna',
 'Parrish, Mrs. (Lutie Davis)',
 'Smith, Mr. Thomas',
 'Asplund, Master Edvin Rojj Felix',
 'Taussig, Mr. Emil',
 'Harrison, Mr. William',
 'Henry, Miss Delia',
 'Reeves, Mr. David',
 'Panula, Mr. Ernesti Arvid',
 'Persson, Mr. Ernst Ulrik',
 'Graham, Mrs. William Thompson (Edith Junkins)',
 'Bissette, Miss Amelia',
 'Cairns, Mr. Alexander',
 'Tornquist, Mr. William Henry',
 'Mellinger, Mrs. (Elizabeth Anne Maidment)',
 'Natsch, Mr. Charles H',
 'Healy, Miss Hanora "Nora"',
 'Andrews, Miss Kornelia Theodosia',
 'Lindblom, Miss Augusta Charlotta',
 'Parkes, Mr. Francis "Frank"',
 'Rice, Master Eric',
 'Abbott, Mrs. Stanton (Rosa Hunt)',
 'Duane, Mr. Frank',
 'Olsson, Mr. Nils Johan Goransson',
 'de Pelsmaeker, Mr. Alfons',
 'Dorking, Mr. Edward Arthur',
 'Smith, Mr. Richard William',
 'Stankovic, Mr. Ivan',
 'de Mulder, Mr. Theodore',
 'Naidenoff, Mr. Penko',
 'Hosono, Mr. Masabumi',
 'Connolly, Miss Kate',
 'Barber, Miss Ellen "Nellie"',
 'Bishop, Mrs. Dickinson H (Helen Walton)',
 'Levy, Mr. Rene Jacques',
 'Haas, Miss Aloisia',
 'Mineff, Mr. Ivan',
 'Lewy, Mr. Ervin G',
 'Hanna, Mr. Mansour',
 'Allison, Miss Helen Loraine',
 'Saalfeld, Mr. Adolphe',
 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
 'Kelly, Miss Anna Katherine "Annie Kate"',
 'McCoy, Mr. Bernard',
 'Johnson, Mr. William Cahoone Jr',
 'Keane, Miss Nora A',
 'Williams, Mr. Howard Hugh "Harry"',
 'Allison, Master Hudson Trevor',
 'Fleming, Miss Margaret',
 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
 'Abelson, Mr. Samuel',
 'Francatelli, Miss Laura Mabel',
 'Hays, Miss Margaret Bechstein',
 'Ryerson, Miss Emily Borie',
 'Lahtinen, Mrs. William (Anna Sylfven)',
 'Hendekovic, Mr. Ignjac',
 'Hart, Mr. Benjamin',
 'Nilsson, Miss Helmina Josefina',
 'Kantor, Mrs. Sinai (Miriam Sternin)',
 'Moraweck, Dr. Ernest',
 'Wick, Miss Mary Natalie',
 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
 'Dennis, Mr. Samuel',
 'Danoff, Mr. Yoto',
 'Slayter, Miss Hilda Mary',
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
 'Sage, Mr. George John Jr',
 'Young, Miss Marie Grice',
 'Nysveen, Mr. Johan Hansen',
 'Ball, Mrs. (Ada E Hall)',
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
 'Hippach, Miss Jean Gertrude',
 'McCoy, Miss Agnes',
 'Partner, Mr. Austen',
 'Graham, Mr. George Edward',
 'Vander Planke, Mr. Leo Edmondus',
 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
 'Denkoff, Mr. Mitto',
 'Pears, Mr. Thomas Clinton',
 'Burns, Miss Elizabeth Margaret',
 'Dahl, Mr. Karl Edwart',
 'Blackwell, Mr. Stephen Weart',
 'Navratil, Master Edmond Roger',
 'Fortune, Miss Alice Elizabeth',
 'Collander, Mr. Erik Gustaf',
 'Sedgwick, Mr. Charles Frederick Waddington',
 'Fox, Mr. Stanley Hubert',
 'Brown, Miss Amelia "Mildred"',
 'Smith, Miss Marion Elsie',
 'Davison, Mrs. Thomas Henry (Mary E Finck)',
 'Coutts, Master William Loch "William"',
 'Dimic, Mr. Jovan',
 'Odahl, Mr. Nils Martin',
 'Williams-Lambert, Mr. Fletcher Fellows',
 'Elias, Mr. Tannous',
 'Arnold-Franchi, Mr. Josef',
 'Yousif, Mr. Wazli',
 'Vanden Steen, Mr. Leo Peter',
 'Bowerman, Miss Elsie Edith',
 'Funk, Miss Annie Clemmer',
 'McGovern, Miss Mary',
 'Mockler, Miss Helen Mary "Ellie"',
 'Skoog, Mr. Wilhelm',
 'del Carlo, Mr. Sebastiano',
 'Barbara, Mrs. (Catherine David)',
 'Asim, Mr. Adola',
 "O'Brien, Mr. Thomas",
 'Adahl, Mr. Mauritz Nils Martin',
 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
 'Moussa, Mrs. (Mantoura Boulos)',
 'Jermyn, Miss Annie',
 'Aubart, Mme. Leontine Pauline',
 'Harder, Mr. George Achilles',
 'Wiklund, Mr. Jakob Alfred',
 'Beavan, Mr. William Thomas',
 'Ringhini, Mr. Sante',
 'Palsson, Miss Stina Viola',
 'Meyer, Mrs. Edgar Joseph (Leila Saks)',
 'Landergren, Miss Aurora Adelia',
 'Widener, Mr. Harry Elkins',
 'Betros, Mr. Tannous',
 'Gustafsson, Mr. Karl Gideon',
 'Bidois, Miss Rosalie',
 'Nakid, Miss Maria ("Mary")',
 'Tikkanen, Mr. Juho',
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
 'Plotcharsky, Mr. Vasil',
 'Davies, Mr. Charles Henry',
 'Goodwin, Master Sidney Leonard',
 'Buss, Miss Kate',
 'Sadlier, Mr. Matthew',
 'Lehmann, Miss Bertha',
 'Carter, Mr. William Ernest',
 'Jansson, Mr. Carl Olof',
 'Gustafsson, Mr. Johan Birger',
 'Newell, Miss Marjorie',
 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
 'Johansson, Mr. Erik',
 'Olsson, Miss Elina',
 'McKane, Mr. Peter David',
 'Pain, Dr. Alfred',
 'Trout, Mrs. William H (Jessie L)',
 'Niskanen, Mr. Juha',
 'Adams, Mr. John',
 'Jussila, Miss Mari Aina',
 'Hakkarainen, Mr. Pekka Pietari',
 'Oreskovic, Miss Marija',
 'Gale, Mr. Shadrach',
 'Widegren, Mr. Carl/Charles Peter',
 'Richards, Master William Rowe',
 'Birkeland, Mr. Hans Martin Monsen',
 'Lefebre, Miss Ida',
 'Sdycoff, Mr. Todor',
 'Hart, Mr. Henry',
 'Minahan, Miss Daisy E',
 'Cunningham, Mr. Alfred Fleming',
 'Sundman, Mr. Johan Julian',
 'Meek, Mrs. Thomas (Annie Louise Rowley)',
 'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
 'Silven, Miss Lyyli Karoliina',
 'Matthews, Mr. William John',
 'Van Impe, Miss Catharina',
 'Gheorgheff, Mr. Stanio',
 'Charters, Mr. David',
 'Zimmerman, Mr. Leo',
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
 'Rosblom, Mr. Viktor Richard',
 'Wiseman, Mr. Phillippe',
 'Clarke, Mrs. Charles V (Ada Maria Winfield)',
 'Phillips, Miss Kate Florence ("Mrs Kate Louise Phillips Marshall")',
 'Flynn, Mr. James',
 'Pickard, Mr. Berk (Berk Trembisky)',
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
 'Thorneycroft, Mrs. Percival (Florence Kate White)',
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
 'Kallio, Mr. Nikolai Erland',
 'Silvey, Mr. William Baird',
 'Carter, Miss Lucile Polk',
 'Ford, Miss Doolina Margaret "Daisy"',
 'Richards, Mrs. Sidney (Emily Hocking)',
 'Fortune, Mr. Mark',
 'Kvillner, Mr. Johan Henrik Johannesson',
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)',
 'Hampe, Mr. Leon',
 'Petterson, Mr. Johan Emil',
 'Reynaldo, Ms. Encarnacion',
 'Johannesen-Bratthammer, Mr. Bernt',
 'Dodge, Master Washington',
 'Mellinger, Miss Madeleine Violet',
 'Seward, Mr. Frederic Kimber',
 'Baclini, Miss Marie Catherine',
 'Peuchen, Major. Arthur Godfrey',
 'West, Mr. Edwy Arthur',
 'Hagland, Mr. Ingvald Olai Olsen',
 'Foreman, Mr. Benjamin Laventall',
 'Goldenberg, Mr. Samuel L',
 'Peduzzi, Mr. Joseph',
 'Jalsevac, Mr. Ivan',
 'Millet, Mr. Francis Davis',
 'Kenyon, Mrs. Frederick R (Marion)',
 'Toomey, Miss Ellen',
 "O'Connor, Mr. Maurice",
 'Anderson, Mr. Harry',
 'Morley, Mr. William',
 'Gee, Mr. Arthur H',
 'Milling, Mr. Jacob Christian',
 'Maisner, Mr. Simon',
 'Goncalves, Mr. Manuel Estanslas',
 'Campbell, Mr. William',
 'Smart, Mr. John Montgomery',
 'Scanlan, Mr. James',
 'Baclini, Miss Helene Barbara',
 'Keefe, Mr. Arthur',
 'Cacic, Mr. Luka',
 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
 'Strandberg, Miss Ida Sofia',
 'Clifford, Mr. George Quincy',
 'Renouf, Mr. Peter Henry',
 'Braund, Mr. Lewis Richard',
 'Karlsson, Mr. Nils August',
 'Hirvonen, Miss Hildur E',
 'Goodwin, Master Harold Victor',
 'Frost, Mr. Anthony Wood "Archie"',
 'Rouse, Mr. Richard Henry',
 'Turkula, Mrs. (Hedwig)',
 'Bishop, Mr. Dickinson H',
 'Lefebre, Miss Jeannie',
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
 'Kent, Mr. Edward Austin',
 'Somerton, Mr. Francis William',
 'Coutts, Master Eden Leslie "Neville"',
 'Hagland, Mr. Konrad Mathias Reiersen',
 'Windelov, Mr. Einar',
 'Molson, Mr. Harry Markland',
 'Artagaveytia, Mr. Ramon',
 'Stanley, Mr. Edward Roland',
 'Yousseff, Mr. Gerious',
 'Eustis, Miss Elizabeth Mussey',
 'Shellard, Mr. Frederick William',
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
 'Svensson, Mr. Olof',
 'Calic, Mr. Petar',
 'Canavan, Miss Mary',
 "O'Sullivan, Miss Bridget Mary",
 'Laitinen, Miss Kristina Sofia',
 'Maioni, Miss Roberta',
 'Penasco y Castellana, Mr. Victor de Satode',
 'Quick, Mrs. Frederick Charles (Jane Richards)',
 'Bradley, Mr. George ("George Arthur Brayton")',
 'Olsen, Mr. Henry Margido',
 'Lang, Mr. Fang',
 'Daly, Mr. Eugene Patrick',
 'Webber, Mr. James',
 'McGough, Mr. James Robert',
 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
 'Coleff, Mr. Satio',
 'Walker, Mr. William Anderson',
 'Lemore, Mrs. (Amelia Milley)',
 'Ryan, Mr. Patrick',
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
 'Pavlovic, Mr. Stefo',
 'Perreault, Miss Anne',
 'Vovk, Mr. Janko',
 'Lahoud, Mr. Sarkis',
 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
 'Kassem, Mr. Fared',
 'Farrell, Mr. James',
 'Ridsdale, Miss Lucy',
 'Farthing, Mr. John',
 'Salonen, Mr. Johan Werner',
 'Hocking, Mr. Richard George',
 'Quick, Miss Phyllis May',
 'Toufik, Mr. Nakli',
 'Elias, Mr. Joseph Jr',
 'Peter, Mrs. Catherine (Catherine Rizk)',
 'Cacic, Miss Marija',
 'Hart, Miss Eva Miriam',
 'Butt, Major. Archibald Willingham',
 'LeRoy, Miss Bertha',
 'Risien, Mr. Samuel Beard',
 'Frolicher, Miss Hedwig Margaritha',
 'Crosby, Miss Harriet R',
 'Andersson, Miss Ingeborg Constanzia',
 'Andersson, Miss Sigrid Elisabeth',
 'Beane, Mr. Edward',
 'Douglas, Mr. Walter Donald',
 'Nicholson, Mr. Arthur Ernest',
 'Beane, Mrs. Edward (Ethel Clarke)',
 'Padro y Manent, Mr. Julian',
 'Goldsmith, Mr. Frank John',
 'Davies, Master John Morgan Jr',
 'Thayer, Mr. John Borland Jr',
 'Sharp, Mr. Percival James R',
 "O'Brien, Mr. Timothy",
 'Leeni, Mr. Fahim ("Philip Zenni")',
 'Ohman, Miss Velin',
 'Wright, Mr. George',
 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
 'Robbins, Mr. Victor',
 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
 'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
 'Morrow, Mr. Thomas Rowan',
 'Sivic, Mr. Husein',
 'Norman, Mr. Robert Douglas',
 'Simmons, Mr. John',
 'Meanwell, Miss (Marion Ogden)',
 'Davies, Mr. Alfred J',
 'Stoytcheff, Mr. Ilia',
 'Palsson, Mrs. Nils (Alma Cornelia Berglund)',
 'Doharr, Mr. Tannous',
 'Jonsson, Mr. Carl',
 'Harris, Mr. George',
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
 'Flynn, Mr. John Irwin ("Irving")',
 'Kelly, Miss Mary',
 'Rush, Mr. Alfred George John',
 'Patchett, Mr. George',
 'Garside, Miss Ethel',
 'Silvey, Mrs. William Baird (Alice Munger)',
 'Caram, Mrs. Joseph (Maria Elias)',
 'Jussila, Mr. Eiriik',
 'Christy, Miss Julie Rachel',
 'Thayer, Mrs. John Borland (Marian Longstreth Morris)',
 'Downton, Mr. William James',
 'Ross, Mr. John Hugo',
 'Paulner, Mr. Uscher',
 'Taussig, Miss Ruth',
 'Jarvis, Mr. John Denzil',
 'Frolicher-Stehli, Mr. Maxmillian',
 'Gilinski, Mr. Eliezer',
 'Murdlin, Mr. Joseph',
 'Rintamaki, Mr. Matti',
 'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
 'Elsbury, Mr. William James',
 'Bourke, Miss Mary',
 'Chapman, Mr. John Henry',
 'Van Impe, Mr. Jean Baptiste',
 'Leitch, Miss Jessie Wills',
 'Johnson, Mr. Alfred',
 'Boulos, Mr. Hanna',
 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)',
 'Slabenoff, Mr. Petco',
 'Harrington, Mr. Charles H',
 'Torber, Mr. Ernst William',
 'Homer, Mr. Harry ("Mr E Haven")',
 'Lindell, Mr. Edvard Bengtsson',
 'Karaic, Mr. Milan',
 'Daniel, Mr. Robert Williams',
 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',
 'Shutes, Miss Elizabeth W',
 'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
 'Jardin, Mr. Jose Neto',
 'Murphy, Miss Margaret Jane',
 'Horgan, Mr. John',
 'Brocklebank, Mr. William Alfred',
 'Herman, Miss Alice',
 'Danbom, Mr. Ernst Gilbert',
 'Lobb, Mrs. William Arthur (Cordelia K Stanlick)',
 'Becker, Miss Marion Louise',
 'Gavey, Mr. Lawrence',
 'Yasbeck, Mr. Antoni',
 'Kimball, Mr. Edwin Nelson Jr',
 'Nakid, Mr. Sahid',
 'Hansen, Mr. Henry Damsgaard',
 'Bowen, Mr. David John "Dai"',
 'Sutton, Mr. Frederick',
 'Kirkland, Rev. Charles Leonard',
 'Longley, Miss Gretchen Fiske',

8 (2.2) Selecting multiple columns. Name, Age, Fare

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Nasser, Mrs. Nicholas (Adele Achem)',
 'Sandstrom, Miss Marguerite Rut',
 'Bonnell, Miss Elizabeth',
 'Saundercock, Mr. William Henry',
 'Andersson, Mr. Anders Johan',
 'Vestrom, Miss Hulda Amanda Adolfina',
 'Hewlett, Mrs. (Mary D Kingcome) ',
 'Rice, Master Eugene',
 'Williams, Mr. Charles Eugene',
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
 'Masselmani, Mrs. Fatima',
 'Fynney, Mr. Joseph J',
 'Beesley, Mr. Lawrence',
 'McGowan, Miss Anna "Annie"',
 'Sloper, Mr. William Thompson',
 'Palsson, Miss Torborg Danira',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Emir, Mr. Farred Chehab',
 'Fortune, Mr. Charles Alexander',
 'O\'Dwyer, Miss Ellen "Nellie"',
 'Todoroff, Mr. Lalio',
 'Uruchurtu, Don. Manuel E',
 'Spencer, Mrs. William Augustus (Marie Eugenie)',
 'Glynn, Miss Mary Agatha',
 'Wheadon, Mr. Edward H',
 'Meyer, Mr. Edgar Joseph',
 'Holverson, Mr. Alexander Oskar',
 'Mamee, Mr. Hanna',
 'Cann, Mr. Ernest Charles',
 'Vander Planke, Miss Augusta Maria',
 'Nicola-Yarred, Miss Jamila',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
 'Kraeff, Mr. Theodor',
 'Laroche, Miss Simonne Marie Anne Andree',
 'Devaney, Miss Margaret Delia',
 'Rogers, Mr. William John',
 'Lennon, Mr. Denis',
 "O'Driscoll, Miss Bridget",
 'Samaan, Mr. Youssef',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Panula, Master Juha Niilo',
 'Nosworthy, Mr. Richard Cater',
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
 'Ostby, Mr. Engelhart Cornelius',
 'Woolner, Mr. Hugh',
 'Rugg, Miss Emily',
 'Novel, Mr. Mansouer',
 'West, Miss Constance Mirium',
 'Goodwin, Master William Frederick',
 'Sirayanian, Mr. Orsen',
 'Icard, Miss Amelie',
 'Harris, Mr. Henry Birkhardt',
 'Skoog, Master Harald',
 'Stewart, Mr. Albert A',
 'Moubarek, Master Gerios',
 'Nye, Mrs. (Elizabeth Ramell)',
 'Crease, Mr. Ernest James',
 'Andersson, Miss Erna Alexandra',
 'Kink, Mr. Vincenz',
 'Jenkin, Mr. Stephen Curnow',
 'Goodwin, Miss Lillian Amy',
 'Hood, Mr. Ambrose Jr',
 'Chronopoulos, Mr. Apostolos',
 'Bing, Mr. Lee',
 'Moen, Mr. Sigurd Hansen',
 'Staneff, Mr. Ivan',
 'Moutal, Mr. Rahamin Haim',
 'Caldwell, Master Alden Gates',
 'Dowdell, Miss Elizabeth',
 'Waelens, Mr. Achille',
 'Sheerlinck, Mr. Jan Baptist',
 'McDermott, Miss Brigdet Delia',
 'Carrau, Mr. Francisco M',
 'Ilett, Miss Bertha',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Ford, Mr. William Neal',
 'Slocovski, Mr. Selman Francis',
 'Fortune, Miss Mabel Helen',
 'Celotti, Mr. Francesco',
 'Christmann, Mr. Emil',
 'Andreasson, Mr. Paul Edvin',
 'Chaffee, Mr. Herbert Fuller',
 'Dean, Mr. Bertram Frank',
 'Coxon, Mr. Daniel',
 'Shorney, Mr. Charles Joseph',
 'Goldschmidt, Mr. George B',
 'Greenfield, Mr. William Bertram',
 'Doling, Mrs. John T (Ada Julia Bone)',
 'Kantor, Mr. Sinai',
 'Petranec, Miss Matilda',
 'Petroff, Mr. Pastcho ("Pentcho")',
 'White, Mr. Richard Frasar',
 'Johansson, Mr. Gustaf Joel',
 'Gustafsson, Mr. Anders Vilhelm',
 'Mionoff, Mr. Stoytcho',
 'Salkjelsvik, Miss Anna Kristine',
 'Moss, Mr. Albert Johan',
 'Rekic, Mr. Tido',
 'Moran, Miss Bertha',
 'Porter, Mr. Walter Chamberlain',
 'Zabour, Miss Hileni',
 'Barton, Mr. David John',
 'Jussila, Miss Katriina',
 'Attalah, Miss Malake',
 'Pekoniemi, Mr. Edvard',
 'Connors, Mr. Patrick',
 'Turpin, Mr. William John Robert',
 'Baxter, Mr. Quigg Edmond',
 'Andersson, Miss Ellis Anna Maria',
 'Hickman, Mr. Stanley George',
 'Moore, Mr. Leonard Charles',
 'Nasser, Mr. Nicholas',
 'Webber, Miss Susan',
 'White, Mr. Percival Wayland',
 'Nicola-Yarred, Master Elias',
 'McMahon, Mr. Martin',
 'Madsen, Mr. Fridtjof Arne',
 'Peter, Miss Anna',
 'Ekstrom, Mr. Johan',
 'Drazenoic, Mr. Jozef',
 'Coelho, Mr. Domingos Fernandeo',
 'Robins, Mrs. Alexander A (Grace Charity Laury)',
 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
 'Sobey, Mr. Samuel James Hayden',
 'Richard, Mr. Emile',
 'Newsom, Miss Helen Monypeny',
 'Futrelle, Mr. Jacques Heath',
 'Osen, Mr. Olaf Elon',
 'Giglio, Mr. Victor',
 'Boulos, Mrs. Joseph (Sultana)',
 'Nysten, Miss Anna Sofia',
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
 'Burke, Mr. Jeremiah',
 'Andrew, Mr. Edgardo Samuel',
 'Nicholls, Mr. Joseph Charles',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Ford, Miss Robina Maggie "Ruby"',
 'Navratil, Mr. Michel ("Louis M Hoffman")',
 'Byles, Rev. Thomas Roussel Davids',
 'Bateman, Rev. Robert James',
 'Pears, Mrs. Thomas (Edith Wearne)',
 'Meo, Mr. Alfonzo',
 'van Billiard, Mr. Austin Blyler',
 'Olsen, Mr. Ole Martin',
 'Williams, Mr. Charles Duane',
 'Gilnagh, Miss Katherine "Katie"',
 'Corn, Mr. Harry',
 'Smiljanic, Mr. Mile',
 'Sage, Master Thomas Henry',
 'Cribb, Mr. John Hatfield',
 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
 'Bengtsson, Mr. John Viktor',
 'Calic, Mr. Jovo',
 'Panula, Master Eino Viljami',
 'Goldsmith, Master Frank John William "Frankie"',
 'Chibnall, Mrs. (Edith Martha Bowerman)',
 'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
 'Baumann, Mr. John D',
 'Ling, Mr. Lee',
 'Van der hoef, Mr. Wyckoff',
 'Rice, Master Arthur',
 'Johnson, Miss Eleanor Ileen',
 'Sivola, Mr. Antti Wilhelm',
 'Smith, Mr. James Clinch',
 'Klasen, Mr. Klas Albin',
 'Lefebre, Master Henry Forbes',
 'Isham, Miss Ann Elizabeth',
 'Hale, Mr. Reginald',
 'Leonard, Mr. Lionel',
 'Sage, Miss Constance Gladys',
 'Pernot, Mr. Rene',
 'Asplund, Master Clarence Gustaf Hugo',
 'Becker, Master Richard F',
 'Kink-Heilmann, Miss Luise Gretchen',
 'Rood, Mr. Hugh Roscoe',
 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)',
 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
 'Bourke, Mr. John',
 'Turcin, Mr. Stjepan',
 'Pinsky, Mrs. (Rosa)',
 'Carbines, Mr. William',
 'Andersen-Jensen, Miss Carla Christine Nielsine',
 'Navratil, Master Michel M',
 'Brown, Mrs. James Joseph (Margaret Tobin)',
 'Lurette, Miss Elise',
 'Mernagh, Mr. Robert',
 'Olsen, Mr. Karl Siegwart Andreas',
 'Madigan, Miss Margaret "Maggie"',
 'Yrois, Miss Henriette ("Mrs Harbeck")',
 'Vande Walle, Mr. Nestor Cyriel',
 'Sage, Mr. Frederick',
 'Johanson, Mr. Jakob Alfred',
 'Youseff, Mr. Gerious',
 'Cohen, Mr. Gurshon "Gus"',
 'Strom, Miss Telma Matilda',
 'Backstrom, Mr. Karl Alfred',
 'Albimona, Mr. Nassef Cassem',
 'Carr, Miss Helen "Ellen"',
 'Blank, Mr. Henry',
 'Ali, Mr. Ahmed',
 'Cameron, Miss Clear Annie',
 'Perkin, Mr. John Henry',
 'Givard, Mr. Hans Kristensen',
 'Kiernan, Mr. Philip',
 'Newell, Miss Madeleine',
 'Honkanen, Miss Eliina',
 'Jacobsohn, Mr. Sidney Samuel',
 'Bazzani, Miss Albina',
 'Harris, Mr. Walter',
 'Sunderland, Mr. Victor Francis',
 'Bracken, Mr. James H',
 'Green, Mr. George Henry',
 'Nenkoff, Mr. Christo',
 'Hoyt, Mr. Frederick Maxfield',
 'Berglund, Mr. Karl Ivar Sven',
 'Mellors, Mr. William John',
 'Lovell, Mr. John Hall ("Henry")',
 'Fahlstrom, Mr. Arne Jonas',
 'Lefebre, Miss Mathilde',
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
 'Larsson, Mr. Bengt Edvin',
 'Sjostedt, Mr. Ernst Adolf',
 'Asplund, Miss Lillian Gertrud',
 'Leyson, Mr. Robert William Norman',
 'Harknett, Miss Alice Phoebe',
 'Hold, Mr. Stephen',
 'Collyer, Miss Marjorie "Lottie"',
 'Pengelly, Mr. Frederick William',
 'Hunt, Mr. George Henry',
 'Zabour, Miss Thamine',
 'Murphy, Miss Katherine "Kate"',
 'Coleridge, Mr. Reginald Charles',
 'Maenpaa, Mr. Matti Alexanteri',
 'Attalah, Mr. Sleiman',
 'Minahan, Dr. William Edward',
 'Lindahl, Miss Agda Thorilda Viktoria',
 'Hamalainen, Mrs. William (Anna)',
 'Beckwith, Mr. Richard Leonard',
 'Carter, Rev. Ernest Courtenay',
 'Reed, Mr. James George',
 'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
 'Stead, Mr. William Thomas',
 'Lobb, Mr. William Arthur',
 'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
 'Touma, Mrs. Darwis (Hanne Youssef Razi)',
 'Thorne, Mrs. Gertrude Maybelle',
 'Cherry, Miss Gladys',
 'Ward, Miss Anna',
 'Parrish, Mrs. (Lutie Davis)',
 'Smith, Mr. Thomas',
 'Asplund, Master Edvin Rojj Felix',
 'Taussig, Mr. Emil',
 'Harrison, Mr. William',
 'Henry, Miss Delia',
 'Reeves, Mr. David',
 'Panula, Mr. Ernesti Arvid',
 'Persson, Mr. Ernst Ulrik',
 'Graham, Mrs. William Thompson (Edith Junkins)',
 'Bissette, Miss Amelia',
 'Cairns, Mr. Alexander',
 'Tornquist, Mr. William Henry',
 'Mellinger, Mrs. (Elizabeth Anne Maidment)',
 'Natsch, Mr. Charles H',
 'Healy, Miss Hanora "Nora"',
 'Andrews, Miss Kornelia Theodosia',
 'Lindblom, Miss Augusta Charlotta',
 'Parkes, Mr. Francis "Frank"',
 'Rice, Master Eric',
 'Abbott, Mrs. Stanton (Rosa Hunt)',
 'Duane, Mr. Frank',
 'Olsson, Mr. Nils Johan Goransson',
 'de Pelsmaeker, Mr. Alfons',
 'Dorking, Mr. Edward Arthur',
 'Smith, Mr. Richard William',
 'Stankovic, Mr. Ivan',
 'de Mulder, Mr. Theodore',
 'Naidenoff, Mr. Penko',
 'Hosono, Mr. Masabumi',
 'Connolly, Miss Kate',
 'Barber, Miss Ellen "Nellie"',
 'Bishop, Mrs. Dickinson H (Helen Walton)',
 'Levy, Mr. Rene Jacques',
 'Haas, Miss Aloisia',
 'Mineff, Mr. Ivan',
 'Lewy, Mr. Ervin G',
 'Hanna, Mr. Mansour',
 'Allison, Miss Helen Loraine',
 'Saalfeld, Mr. Adolphe',
 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
 'Kelly, Miss Anna Katherine "Annie Kate"',
 'McCoy, Mr. Bernard',
 'Johnson, Mr. William Cahoone Jr',
 'Keane, Miss Nora A',
 'Williams, Mr. Howard Hugh "Harry"',
 'Allison, Master Hudson Trevor',
 'Fleming, Miss Margaret',
 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
 'Abelson, Mr. Samuel',
 'Francatelli, Miss Laura Mabel',
 'Hays, Miss Margaret Bechstein',
 'Ryerson, Miss Emily Borie',
 'Lahtinen, Mrs. William (Anna Sylfven)',
 'Hendekovic, Mr. Ignjac',
 'Hart, Mr. Benjamin',
 'Nilsson, Miss Helmina Josefina',
 'Kantor, Mrs. Sinai (Miriam Sternin)',
 'Moraweck, Dr. Ernest',
 'Wick, Miss Mary Natalie',
 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
 'Dennis, Mr. Samuel',
 'Danoff, Mr. Yoto',
 'Slayter, Miss Hilda Mary',
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
 'Sage, Mr. George John Jr',
 'Young, Miss Marie Grice',
 'Nysveen, Mr. Johan Hansen',
 'Ball, Mrs. (Ada E Hall)',
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
 'Hippach, Miss Jean Gertrude',
 'McCoy, Miss Agnes',
 'Partner, Mr. Austen',
 'Graham, Mr. George Edward',
 'Vander Planke, Mr. Leo Edmondus',
 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
 'Denkoff, Mr. Mitto',
 'Pears, Mr. Thomas Clinton',
 'Burns, Miss Elizabeth Margaret',
 'Dahl, Mr. Karl Edwart',
 'Blackwell, Mr. Stephen Weart',
 'Navratil, Master Edmond Roger',
 'Fortune, Miss Alice Elizabeth',
 'Collander, Mr. Erik Gustaf',
 'Sedgwick, Mr. Charles Frederick Waddington',
 'Fox, Mr. Stanley Hubert',
 'Brown, Miss Amelia "Mildred"',
 'Smith, Miss Marion Elsie',
 'Davison, Mrs. Thomas Henry (Mary E Finck)',
 'Coutts, Master William Loch "William"',
 'Dimic, Mr. Jovan',
 'Odahl, Mr. Nils Martin',
 'Williams-Lambert, Mr. Fletcher Fellows',
 'Elias, Mr. Tannous',
 'Arnold-Franchi, Mr. Josef',
 'Yousif, Mr. Wazli',
 'Vanden Steen, Mr. Leo Peter',
 'Bowerman, Miss Elsie Edith',
 'Funk, Miss Annie Clemmer',
 'McGovern, Miss Mary',
 'Mockler, Miss Helen Mary "Ellie"',
 'Skoog, Mr. Wilhelm',
 'del Carlo, Mr. Sebastiano',
 'Barbara, Mrs. (Catherine David)',
 'Asim, Mr. Adola',
 "O'Brien, Mr. Thomas",
 'Adahl, Mr. Mauritz Nils Martin',
 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
 'Moussa, Mrs. (Mantoura Boulos)',
 'Jermyn, Miss Annie',
 'Aubart, Mme. Leontine Pauline',
 'Harder, Mr. George Achilles',
 'Wiklund, Mr. Jakob Alfred',
 'Beavan, Mr. William Thomas',
 'Ringhini, Mr. Sante',
 'Palsson, Miss Stina Viola',
 'Meyer, Mrs. Edgar Joseph (Leila Saks)',
 'Landergren, Miss Aurora Adelia',
 'Widener, Mr. Harry Elkins',
 'Betros, Mr. Tannous',
 'Gustafsson, Mr. Karl Gideon',
 'Bidois, Miss Rosalie',
 'Nakid, Miss Maria ("Mary")',
 'Tikkanen, Mr. Juho',
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
 'Plotcharsky, Mr. Vasil',
 'Davies, Mr. Charles Henry',
 'Goodwin, Master Sidney Leonard',
 'Buss, Miss Kate',
 'Sadlier, Mr. Matthew',
 'Lehmann, Miss Bertha',
 'Carter, Mr. William Ernest',
 'Jansson, Mr. Carl Olof',
 'Gustafsson, Mr. Johan Birger',
 'Newell, Miss Marjorie',
 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
 'Johansson, Mr. Erik',
 'Olsson, Miss Elina',
 'McKane, Mr. Peter David',
 'Pain, Dr. Alfred',
 'Trout, Mrs. William H (Jessie L)',
 'Niskanen, Mr. Juha',
 'Adams, Mr. John',
 'Jussila, Miss Mari Aina',
 'Hakkarainen, Mr. Pekka Pietari',
 'Oreskovic, Miss Marija',
 'Gale, Mr. Shadrach',
 'Widegren, Mr. Carl/Charles Peter',
 'Richards, Master William Rowe',
 'Birkeland, Mr. Hans Martin Monsen',
 'Lefebre, Miss Ida',
 'Sdycoff, Mr. Todor',
 'Hart, Mr. Henry',
 'Minahan, Miss Daisy E',
 'Cunningham, Mr. Alfred Fleming',
 'Sundman, Mr. Johan Julian',
 'Meek, Mrs. Thomas (Annie Louise Rowley)',
 'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
 'Silven, Miss Lyyli Karoliina',
 'Matthews, Mr. William John',
 'Van Impe, Miss Catharina',
 'Gheorgheff, Mr. Stanio',
 'Charters, Mr. David',
 'Zimmerman, Mr. Leo',
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
 'Rosblom, Mr. Viktor Richard',
 'Wiseman, Mr. Phillippe',
 'Clarke, Mrs. Charles V (Ada Maria Winfield)',
 'Phillips, Miss Kate Florence ("Mrs Kate Louise Phillips Marshall")',
 'Flynn, Mr. James',
 'Pickard, Mr. Berk (Berk Trembisky)',
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
 'Thorneycroft, Mrs. Percival (Florence Kate White)',
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
 'Kallio, Mr. Nikolai Erland',
 'Silvey, Mr. William Baird',
 'Carter, Miss Lucile Polk',
 'Ford, Miss Doolina Margaret "Daisy"',
 'Richards, Mrs. Sidney (Emily Hocking)',
 'Fortune, Mr. Mark',
 'Kvillner, Mr. Johan Henrik Johannesson',
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)',
 'Hampe, Mr. Leon',
 'Petterson, Mr. Johan Emil',
 'Reynaldo, Ms. Encarnacion',
 'Johannesen-Bratthammer, Mr. Bernt',
 'Dodge, Master Washington',
 'Mellinger, Miss Madeleine Violet',
 'Seward, Mr. Frederic Kimber',
 'Baclini, Miss Marie Catherine',
 'Peuchen, Major. Arthur Godfrey',
 'West, Mr. Edwy Arthur',
 'Hagland, Mr. Ingvald Olai Olsen',
 'Foreman, Mr. Benjamin Laventall',
 'Goldenberg, Mr. Samuel L',
 'Peduzzi, Mr. Joseph',
 'Jalsevac, Mr. Ivan',
 'Millet, Mr. Francis Davis',
 'Kenyon, Mrs. Frederick R (Marion)',
 'Toomey, Miss Ellen',
 "O'Connor, Mr. Maurice",
 'Anderson, Mr. Harry',
 'Morley, Mr. William',
 'Gee, Mr. Arthur H',
 'Milling, Mr. Jacob Christian',
 'Maisner, Mr. Simon',
 'Goncalves, Mr. Manuel Estanslas',
 'Campbell, Mr. William',
 'Smart, Mr. John Montgomery',
 'Scanlan, Mr. James',
 'Baclini, Miss Helene Barbara',
 'Keefe, Mr. Arthur',
 'Cacic, Mr. Luka',
 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
 'Strandberg, Miss Ida Sofia',
 'Clifford, Mr. George Quincy',
 'Renouf, Mr. Peter Henry',
 'Braund, Mr. Lewis Richard',
 'Karlsson, Mr. Nils August',
 'Hirvonen, Miss Hildur E',
 'Goodwin, Master Harold Victor',
 'Frost, Mr. Anthony Wood "Archie"',
 'Rouse, Mr. Richard Henry',
 'Turkula, Mrs. (Hedwig)',
 'Bishop, Mr. Dickinson H',
 'Lefebre, Miss Jeannie',
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
 'Kent, Mr. Edward Austin',
 'Somerton, Mr. Francis William',
 'Coutts, Master Eden Leslie "Neville"',
 'Hagland, Mr. Konrad Mathias Reiersen',
 'Windelov, Mr. Einar',
 'Molson, Mr. Harry Markland',
 'Artagaveytia, Mr. Ramon',
 'Stanley, Mr. Edward Roland',
 'Yousseff, Mr. Gerious',
 'Eustis, Miss Elizabeth Mussey',
 'Shellard, Mr. Frederick William',
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
 'Svensson, Mr. Olof',
 'Calic, Mr. Petar',
 'Canavan, Miss Mary',
 "O'Sullivan, Miss Bridget Mary",
 'Laitinen, Miss Kristina Sofia',
 'Maioni, Miss Roberta',
 'Penasco y Castellana, Mr. Victor de Satode',
 'Quick, Mrs. Frederick Charles (Jane Richards)',
 'Bradley, Mr. George ("George Arthur Brayton")',
 'Olsen, Mr. Henry Margido',
 'Lang, Mr. Fang',
 'Daly, Mr. Eugene Patrick',
 'Webber, Mr. James',
 'McGough, Mr. James Robert',
 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
 'Coleff, Mr. Satio',
 'Walker, Mr. William Anderson',
 'Lemore, Mrs. (Amelia Milley)',
 'Ryan, Mr. Patrick',
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
 'Pavlovic, Mr. Stefo',
 'Perreault, Miss Anne',
 'Vovk, Mr. Janko',
 'Lahoud, Mr. Sarkis',
 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
 'Kassem, Mr. Fared',
 'Farrell, Mr. James',
 'Ridsdale, Miss Lucy',
 'Farthing, Mr. John',
 'Salonen, Mr. Johan Werner',
 'Hocking, Mr. Richard George',
 'Quick, Miss Phyllis May',
 'Toufik, Mr. Nakli',
 'Elias, Mr. Joseph Jr',
 'Peter, Mrs. Catherine (Catherine Rizk)',
 'Cacic, Miss Marija',
 'Hart, Miss Eva Miriam',
 'Butt, Major. Archibald Willingham',
 'LeRoy, Miss Bertha',
 'Risien, Mr. Samuel Beard',
 'Frolicher, Miss Hedwig Margaritha',
 'Crosby, Miss Harriet R',
 'Andersson, Miss Ingeborg Constanzia',
 'Andersson, Miss Sigrid Elisabeth',
 'Beane, Mr. Edward',
 'Douglas, Mr. Walter Donald',
 'Nicholson, Mr. Arthur Ernest',
 'Beane, Mrs. Edward (Ethel Clarke)',
 'Padro y Manent, Mr. Julian',
 'Goldsmith, Mr. Frank John',
 'Davies, Master John Morgan Jr',
 'Thayer, Mr. John Borland Jr',
 'Sharp, Mr. Percival James R',
 "O'Brien, Mr. Timothy",
 'Leeni, Mr. Fahim ("Philip Zenni")',
 'Ohman, Miss Velin',
 'Wright, Mr. George',
 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
 'Robbins, Mr. Victor',
 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
 'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
 'Morrow, Mr. Thomas Rowan',
 'Sivic, Mr. Husein',
 'Norman, Mr. Robert Douglas',
 'Simmons, Mr. John',
 'Meanwell, Miss (Marion Ogden)',
 'Davies, Mr. Alfred J',
 'Stoytcheff, Mr. Ilia',
 'Palsson, Mrs. Nils (Alma Cornelia Berglund)',
 'Doharr, Mr. Tannous',
 'Jonsson, Mr. Carl',
 'Harris, Mr. George',
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
 'Flynn, Mr. John Irwin ("Irving")',
 'Kelly, Miss Mary',
 'Rush, Mr. Alfred George John',
 'Patchett, Mr. George',
 'Garside, Miss Ethel',
 'Silvey, Mrs. William Baird (Alice Munger)',
 'Caram, Mrs. Joseph (Maria Elias)',
 'Jussila, Mr. Eiriik',
 'Christy, Miss Julie Rachel',
 'Thayer, Mrs. John Borland (Marian Longstreth Morris)',
 'Downton, Mr. William James',
 'Ross, Mr. John Hugo',
 'Paulner, Mr. Uscher',
 'Taussig, Miss Ruth',
 'Jarvis, Mr. John Denzil',
 'Frolicher-Stehli, Mr. Maxmillian',
 'Gilinski, Mr. Eliezer',
 'Murdlin, Mr. Joseph',
 'Rintamaki, Mr. Matti',
 'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
 'Elsbury, Mr. William James',
 'Bourke, Miss Mary',
 'Chapman, Mr. John Henry',
 'Van Impe, Mr. Jean Baptiste',
 'Leitch, Miss Jessie Wills',
 'Johnson, Mr. Alfred',
 'Boulos, Mr. Hanna',
 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)',
 'Slabenoff, Mr. Petco',
 'Harrington, Mr. Charles H',
 'Torber, Mr. Ernst William',
 'Homer, Mr. Harry ("Mr E Haven")',
 'Lindell, Mr. Edvard Bengtsson',
 'Karaic, Mr. Milan',
 'Daniel, Mr. Robert Williams',
 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',
 'Shutes, Miss Elizabeth W',
 'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
 'Jardin, Mr. Jose Neto',
 'Murphy, Miss Margaret Jane',
 'Horgan, Mr. John',
 'Brocklebank, Mr. William Alfred',
 'Herman, Miss Alice',
 'Danbom, Mr. Ernst Gilbert',
 'Lobb, Mrs. William Arthur (Cordelia K Stanlick)',
 'Becker, Miss Marion Louise',
 'Gavey, Mr. Lawrence',
 'Yasbeck, Mr. Antoni',
 'Kimball, Mr. Edwin Nelson Jr',
 'Nakid, Mr. Sahid',
 'Hansen, Mr. Henry Damsgaard',
 'Bowen, Mr. David John "Dai"',
 'Sutton, Mr. Frederick',
 'Kirkland, Rev. Charles Leonard',
 'Longley, Miss Gretchen Fiske',

8 (2.3) Selecting a single row. Mrs. John Bradley Cumings

[0,
 1,
 1,
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 0,
 8.30088235294118,
 1,
 0,
 'PC 17599',
 69.2833,
 'C85',
 'C',
 61.303638,
 51,
 60.98241764705882]