# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

### Student: Atif M. Mahmud
### SFU ID: atifm@sfu.ca

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [ ]:
import pandas as pd
import os
from pprint import pprint
from IPython.display import display

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [31]:
# Formatting the string as per: https://www.w3schools.com/python/ref_string_format.asp
# Converting the columns pandax index to a basic list so it can easily be printed; otherwise it gave "dtype = str" at the end. Used the help of Claude for this.
print("1.1  The shape of the dataset is {shape} and the columns are {columns}".format(shape = df.shape, columns = list(df.columns)))

# Space
print("\n\n")

# Summary statistics. Data type, description, and where applicable, min, max, mean, and std. dev.
# Got some information from here: https://www.kaggle.com/datasets/yasserh/titanic-dataset
df_summary = pd.DataFrame(index = df.columns, columns = ['Data Type', 'Description', 'Min', 'Max', 'Mean', 'Standard Deviation'])

# Construct a summary data frame from the original data frame
df_summary.loc["PassengerId"] = ["Categorical", "ID of the passenger", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Survived"] = ["Categorical", "Whether or not the passenger survived. 0 = no. 1 = yes", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Pclass"] = ["Categorical", "Which class the passenger was in: 1nd, 2nd, or 3rd", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Name"] = ["Categorical", "Name of the passenger", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Sex"] = ["Categorical", "Sex of the passenger. male or female.", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Age"] = ["Numerical", "Age of the passenger", df["Age"].min(), df["Age"].max(), df["Age"].mean(), df["Age"].std()]
df_summary.loc["SibSp"] = ["Numerical", "Number of siblings/spouses aboard the titanic", df["SibSp"].min(), df["SibSp"].max(), df["SibSp"].mean(), df["SibSp"].std()]
df_summary.loc["Parch"] = ["Numerical", "Number of parents/children aboard the titanic", df["Parch"].min(), df["Parch"].max(), df["Parch"].mean(), df["Parch"].std()]
df_summary.loc["Ticket"] = ["Categorical", "Ticket Number", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Fare"] = ["Numerical", "Fare paid", df["Fare"].min(), df["Fare"].max(), df["Fare"].mean(), df["Fare"].std()]
df_summary.loc["Cabin"] = ["Categorical", "Cabin Number", "N/A", "N/A", "N/A", "N/A"]
df_summary.loc["Embarked"] = ["Categorical", "Port of Embarkation: C = Cherbourg, Q = Queenstown, S = Southampton.", "N/A", "N/A", "N/A", "N/A"]

# Print it
print("1.2 The summary and descriptive data is given below.")
display(df_summary)


# Space
print("\n\n")

# The first 10 rows of the dataframe
print("1.3 The first 10 rows are given below")
display(df.head(10))

1.1  The shape of the dataset is (891, 12) and the columns are ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']



1.2 The summary and descriptive data is given below.

,Data Type,Description,Min,Max,Mean,Standard Deviation
PassengerId,Categorical,ID of the passenger,N/A,N/A,N/A,N/A
Survived,Categorical,Whether or not the passenger survived. 0 = no....,N/A,N/A,N/A,N/A
Pclass,Categorical,"Which class the passenger was in: 1nd, 2nd, or...",N/A,N/A,N/A,N/A
Name,Categorical,Name of the passenger,N/A,N/A,N/A,N/A
Sex,Categorical,Sex of the passenger. male or female.,N/A,N/A,N/A,N/A
Age,Numerical,Age of the passenger,0.42,80.0,29.699118,14.526497
SibSp,Numerical,Number of siblings/spouses aboard the titanic,0,8,0.523008,1.102743
Parch,Numerical,Number of parents/children aboard the titanic,0,6,0.381594,0.806057
Ticket,Categorical,Ticket Number,N/A,N/A,N/A,N/A
Fare,Numerical,Fare paid,0.0,512.3292,32.204208,49.693429
Cabin,Categorical,Cabin Number,N/A,N/A,N/A,N/A
Embarked,Categorical,"Port of Embarkation: C = Cherbourg, Q = Queens...",N/A,N/A,N/A,N/A

1.3 The first 10 rows are given below

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [30]:
# Select the names column
names = pd.DataFrame(df["Name"]) # I am converting it to a DataFrame to make it print nicely using display()

# Alternate way
# names = df["Name"]

# Print it
print("2.1 Names column given below")
display(names)

# Space
print("\n\n")

# Select multiple columns: Name, Sex, Age, Fare
print("2.2 Selecting multiple columns: Name, Sex, Age, Fare")
selected_columns = df[["Name", "Sex", "Age", "Fare"]]
display(selected_columns)

# Space
print("\n\n")

# Select a single row: Mr. James Moran
print("2.3 Selecting a single row: Mr. James Moran")
selected_row = df.loc[df["Name"] == "Moran, Mr. James"]
display(selected_row)

# Space
print("\n\n")

# Select a rectangle
print("2.4 Selecting a rectangular section. Name, Sex, and Age of passengers 100 to 200 (inclusive)")
rectangular_section = df.loc[100:200, "Name" : "Age"]
display(rectangular_section)

2.1 Names column given below

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                        Graham, Miss Margaret Edith
888            Johnston, Miss Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

2.2 Selecting multiple columns: Name, Sex, Age, Fare

                                                  Name     Sex   Age     Fare
0                              Braund, Mr. Owen Harris    male  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  71.2833
2                                Heikkinen, Miss Laina  female  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  53.1000
4                             Allen, Mr. William Henry    male  35.0   8.0500
..                                                 ...     ...   ...      ...
886                              Montvila, Rev. Juozas    male  27.0  13.0000
887                        Graham, Miss Margaret Edith  female  19.0  30.0000
888            Johnston, Miss Catherine Helen "Carrie"  female   NaN  23.4500
889                              Behr, Mr. Karl Howell    male  26.0  30.0000
890                                Dooley, Mr. Patrick    male  32.0   7.7500

[891 rows x 4 columns]

2.3 Selecting a single row: Mr. James Moran

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

2.4 Selecting a rectangular section. Name, Sex, and Age of passengers 100 to 200 (inclusive)

                                      Name     Sex   Age
100                 Petranec, Miss Matilda  female  28.0
101       Petroff, Mr. Pastcho ("Pentcho")    male   NaN
102              White, Mr. Richard Frasar    male  21.0
103             Johansson, Mr. Gustaf Joel    male  33.0
104         Gustafsson, Mr. Anders Vilhelm    male  37.0
..                                     ...     ...   ...
196                    Mernagh, Mr. Robert    male   NaN
197       Olsen, Mr. Karl Siegwart Andreas    male  42.0
198        Madigan, Miss Margaret "Maggie"  female   NaN
199  Yrois, Miss Henriette ("Mrs Harbeck")  female  24.0
200         Vande Walle, Mr. Nestor Cyriel    male  28.0

[101 rows x 3 columns]

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).